import React, { useState } from 'react';
import {
  X, Code2, Copy, Check, Download, Layers, Sparkles,
  FileCode, CheckCircle2, ArrowRight, RefreshCw, Box
} from 'lucide-react';
import { ThemeMode } from './Header';

interface TypeScriptGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentTheme?: ThemeMode;
}

interface DtoEntity {
  id: string;
  name: string;
  javaPackage: string;
  javaSource: string;
  tsType: string;
  zodSchema: string;
}

const DTO_ENTITIES: DtoEntity[] = [
  {
    id: 'OrderRequest',
    name: 'OrderRequest.java',
    javaPackage: 'com.codeflow.studio.dto',
    javaSource: `package com.codeflow.studio.dto;

import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record OrderRequest(
    @NotNull String orderId,
    @NotNull String userId,
    BigDecimal totalAmount,
    List<OrderItemDto> items,
    OrderStatus status,
    Instant createdAt
) {}`,
    tsType: `export type OrderStatus = 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';

export interface OrderItemDto {
  productId: string;
  quantity: number;
  unitPrice: number;
}

export interface OrderRequest {
  orderId: string;
  userId: string;
  totalAmount?: number;
  items: OrderItemDto[];
  status: OrderStatus;
  createdAt: string; // ISO 8601 string
}`,
    zodSchema: `import { z } from 'zod';

export const OrderStatusSchema = z.enum(['PENDING', 'PAID', 'FAILED', 'REFUNDED']);

export const OrderItemDtoSchema = z.object({
  productId: z.string(),
  quantity: z.number().int().positive(),
  unitPrice: z.number(),
});

export const OrderRequestSchema = z.object({
  orderId: z.string().min(1),
  userId: z.string().min(1),
  totalAmount: z.number().optional(),
  items: z.array(OrderItemDtoSchema),
  status: OrderStatusSchema,
  createdAt: z.string().datetime(),
});

export type OrderRequest = z.infer<typeof OrderRequestSchema>;`
  },
  {
    id: 'UserResponseDto',
    name: 'UserResponseDto.java',
    javaPackage: 'com.codeflow.studio.dto',
    javaSource: `package com.codeflow.studio.dto;

import java.time.LocalDateTime;
import java.util.Set;

public record UserResponseDto(
    Long id,
    String username,
    String email,
    Set<String> roles,
    LocalDateTime lastLogin,
    boolean active
) {}`,
    tsType: `export interface UserResponseDto {
  id: number;
  username: string;
  email: string;
  roles: string[];
  lastLogin?: string; // LocalDateTime
  active: boolean;
}`,
    zodSchema: `import { z } from 'zod';

export const UserResponseDtoSchema = z.object({
  id: z.number(),
  username: z.string(),
  email: z.string().email(),
  roles: z.array(z.string()),
  lastLogin: z.string().optional(),
  active: z.boolean(),
});

export type UserResponseDto = z.infer<typeof UserResponseDtoSchema>;`
  },
  {
    id: 'ProductEntity',
    name: 'ProductEntity.java',
    javaPackage: 'com.codeflow.studio.entity',
    javaSource: `package com.codeflow.studio.entity;

import jakarta.persistence.*;
import java.util.UUID;
import java.util.Map;

@Entity
@Table(name = "products")
public class ProductEntity {
    @Id
    private UUID id;
    private String sku;
    private String name;
    private double price;
    private Integer stock;
    
    @ElementCollection
    private Map<String, String> attributes;
}`,
    tsType: `export interface ProductEntity {
  id: string; // UUID
  sku: string;
  name: string;
  price: number;
  stock?: number;
  attributes?: Record<string, string>;
}`,
    zodSchema: `import { z } from 'zod';

export const ProductEntitySchema = z.object({
  id: z.string().uuid(),
  sku: z.string(),
  name: z.string(),
  price: z.number().nonnegative(),
  stock: z.number().int().optional(),
  attributes: z.record(z.string()).optional(),
});

export type ProductEntity = z.infer<typeof ProductEntitySchema>;`
  }
];

export const TypeScriptGeneratorModal: React.FC<TypeScriptGeneratorModalProps> = ({
  isOpen,
  onClose,
  currentTheme = 'NIGHT',
}) => {
  const [selectedDto, setSelectedDto] = useState<DtoEntity>(DTO_ENTITIES[0]);
  const [viewMode, setViewMode] = useState<'TYPESCRIPT' | 'ZOD'>('TYPESCRIPT');
  const [copied, setCopied] = useState<string | null>(null);

  if (!isOpen) return null;

  const isLight = currentTheme === 'NORMAL';
  const isGlass = currentTheme === 'GLASSMORPHISM';
  const isNeumorphic = currentTheme === 'NEUMORPHIC';

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownloadAll = () => {
    const combined = `// Auto-generated by CodeFlow Studio v7.0
// Generated at: ${new Date().toISOString()}

${DTO_ENTITIES.map(d => `// ==========================================
// ${d.name} (${d.javaPackage})
// ==========================================
${viewMode === 'TYPESCRIPT' ? d.tsType : d.zodSchema}
`).join('\n')}`;

    const blob = new Blob([combined], { type: 'text/typescript;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = viewMode === 'TYPESCRIPT' ? 'codeflow-api.generated.ts' : 'codeflow-schemas.generated.ts';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4 bg-black/90 backdrop-blur-md animate-in fade-in duration-200">
      <div
        className={`w-full max-w-5xl max-h-[90vh] flex flex-col rounded-2xl shadow-2xl overflow-hidden border ${
          isLight
            ? 'bg-white border-slate-200 text-slate-900'
            : isGlass
            ? 'bg-[#0f172a] border-cyan-500/40 text-white'
            : isNeumorphic
            ? 'bg-[#1e2330] border-slate-700/50 text-slate-100'
            : 'bg-[#0f172a] border-slate-700 text-white'
        }`}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-700/50 bg-slate-800/30">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-500 to-indigo-500 flex items-center justify-center text-white font-bold shadow-lg shadow-blue-500/20">
              <Code2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-bold tracking-tight">Java DTO ➔ TypeScript Generator</h2>
                <span className="px-2 py-0.5 text-xs font-semibold rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30">
                  TypeSafe Bridge
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Transform Spring Boot JPA Entities & Java Records into strict TypeScript interfaces & Zod runtime schemas
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handleDownloadAll}
              className="flex items-center gap-2 px-3 py-1.5 text-xs font-semibold rounded-lg bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/30 transition"
            >
              <Download className="w-3.5 h-3.5" />
              Download All (.ts)
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Layout */}
        <div className="flex-1 overflow-hidden grid grid-cols-1 md:grid-cols-12">
          {/* Left Sidebar Entity Selector */}
          <div className="md:col-span-4 border-r border-slate-700/50 p-4 space-y-2 overflow-y-auto bg-slate-800/20">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block mb-2">
              Parsed Java Domain Entities
            </span>
            {DTO_ENTITIES.map(dto => (
              <button
                key={dto.id}
                onClick={() => setSelectedDto(dto)}
                className={`w-full text-left p-3 rounded-xl border transition flex flex-col gap-1 ${
                  selectedDto.id === dto.id
                    ? 'bg-blue-500/15 border-blue-500/40 text-blue-300'
                    : 'bg-slate-800/40 border-slate-700/40 text-slate-300 hover:bg-slate-800/70'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold truncate">{dto.name}</span>
                  <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-800 text-slate-400">
                    Java
                  </span>
                </div>
                <code className="text-[11px] font-mono text-slate-400 truncate">{dto.javaPackage}</code>
              </button>
            ))}
          </div>

          {/* Right Dual Code Viewer */}
          <div className="md:col-span-8 flex flex-col overflow-y-auto p-5 space-y-4">
            {/* Top Toolbar */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setViewMode('TYPESCRIPT')}
                  className={`px-3 py-1 text-xs font-bold rounded-lg transition ${
                    viewMode === 'TYPESCRIPT' ? 'bg-blue-500 text-white shadow' : 'bg-slate-800 text-slate-400 hover:text-white'
                  }`}
                >
                  TypeScript Interface
                </button>
                <button
                  onClick={() => setViewMode('ZOD')}
                  className={`px-3 py-1 text-xs font-bold rounded-lg transition ${
                    viewMode === 'ZOD' ? 'bg-blue-500 text-white shadow' : 'bg-slate-800 text-slate-400 hover:text-white'
                  }`}
                >
                  Zod Schema Validator
                </button>
              </div>
              <button
                onClick={() => copyToClipboard(viewMode === 'TYPESCRIPT' ? selectedDto.tsType : selectedDto.zodSchema, 'code')}
                className="flex items-center gap-1.5 px-3 py-1 text-xs font-semibold rounded-lg bg-slate-800 text-slate-300 hover:text-white border border-slate-700"
              >
                {copied === 'code' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied === 'code' ? 'Copied' : 'Copy TS Code'}
              </button>
            </div>

            {/* Side-by-Side Java vs TypeScript View */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 flex-1">
              {/* Java Source */}
              <div className="border border-slate-700/50 rounded-xl overflow-hidden flex flex-col bg-slate-900/60">
                <div className="px-3 py-1.5 bg-slate-800/60 border-b border-slate-700/50 flex items-center justify-between text-xs font-mono text-slate-400">
                  <span>Java Source ({selectedDto.name})</span>
                </div>
                <pre className="p-3 text-xs font-mono text-amber-300/90 flex-1 overflow-x-auto">
                  {selectedDto.javaSource}
                </pre>
              </div>

              {/* Generated TypeScript / Zod */}
              <div className="border border-blue-500/30 rounded-xl overflow-hidden flex flex-col bg-[#0f172a] shadow-inner">
                <div className="px-3 py-1.5 bg-blue-950/40 border-b border-blue-500/30 flex items-center justify-between text-xs font-mono text-blue-300">
                  <span>Generated {viewMode === 'TYPESCRIPT' ? 'TypeScript' : 'Zod Schema'}</span>
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-blue-500/20 text-blue-300">100% Strict</span>
                </div>
                <pre className="p-3 text-xs font-mono text-cyan-300 flex-1 overflow-x-auto">
                  {viewMode === 'TYPESCRIPT' ? selectedDto.tsType : selectedDto.zodSchema}
                </pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
