import { Project, GraphData } from '../types';

export const DEMO_PROJECT_DATA: Project = {
  id: 'demo-ecommerce-store',
  name: 'codeflow-demo-store (E-Commerce Microservice)',
  sourceType: 'GITHUB',
  sourceUrl: 'https://github.com/codeflow-studio/demo-ecommerce-store.git',
  status: 'COMPLETED',
  progressPercentage: 100,
  errorMessage: undefined,
  controllerCount: 7,
  serviceCount: 5,
  repositoryCount: 4,
};

export const DEMO_GRAPH_DATA: GraphData = {
  nodes: [
    {
      id: 'fe_react_app',
      type: 'custom',
      position: { x: 50, y: 100 },
      data: {
        label: 'Storefront (App.tsx)',
        nodeType: 'REACT_COMPONENT',
        layer: 'FRONTEND',
        filePath: 'src/App.tsx',
        annotations: 'React 18, Vite, TailwindCSS, Axios',
      },
    },
    {
      id: 'fe_cart_view',
      type: 'custom',
      position: { x: 50, y: 250 },
      data: {
        label: 'CartCheckout (CartView.tsx)',
        nodeType: 'REACT_COMPONENT',
        layer: 'FRONTEND',
        filePath: 'src/components/CartView.tsx',
        annotations: 'React Component, useState, useEffect, Axios',
      },
    },
    {
      id: 'gw_security',
      type: 'custom',
      position: { x: 250, y: 175 },
      data: {
        label: 'API Gateway',
        nodeType: 'SPRING_CONTROLLER',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/config/SecurityConfig.java',
        annotations: '@RestController, Spring Security 6.x, JwtAuthenticationFilter, CorsFilter',
      },
    },
    {
      id: 'ctrl_admin',
      type: 'custom',
      position: { x: 450, y: 50 },
      data: {
        label: 'AdminController',
        nodeType: 'SPRING_CONTROLLER',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/controller/AdminController.java',
        endpointPath: '/api/v1/admin/login',
        annotations: '@RestController, @PostMapping, @Valid, @CrossOrigin',
      },
    },
    {
      id: 'ctrl_order',
      type: 'custom',
      position: { x: 450, y: 200 },
      data: {
        label: 'OrderController',
        nodeType: 'SPRING_CONTROLLER',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/controller/OrderController.java',
        endpointPath: '/api/v1/orders/checkout',
        annotations: '@RestController, @PostMapping, @Valid, @CrossOrigin',
      },
    },
    {
      id: 'ctrl_payment',
      type: 'custom',
      position: { x: 450, y: 350 },
      data: {
        label: 'PaymentController',
        nodeType: 'SPRING_CONTROLLER',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/controller/PaymentController.java',
        endpointPath: '/api/v1/payments/process',
        annotations: '@RestController, @PostMapping, @Valid',
      },
    },
    {
      id: 'svc_auth',
      type: 'custom',
      position: { x: 650, y: 50 },
      data: {
        label: 'AuthService',
        nodeType: 'SPRING_SERVICE',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/service/AuthService.java',
        annotations: '@Service, @Transactional, PasswordEncoder, JwtTokenProvider',
      },
    },
    {
      id: 'svc_order',
      type: 'custom',
      position: { x: 650, y: 200 },
      data: {
        label: 'OrderService',
        nodeType: 'SPRING_SERVICE',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/service/OrderService.java',
        annotations: '@Service, @Transactional, InventoryValidator',
      },
    },
    {
      id: 'svc_payment',
      type: 'custom',
      position: { x: 650, y: 350 },
      data: {
        label: 'PaymentService',
        nodeType: 'SPRING_SERVICE',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/service/PaymentService.java',
        annotations: '@Service, @Transactional, StripeClient',
      },
    },
    {
      id: 'repo_user',
      type: 'custom',
      position: { x: 850, y: 50 },
      data: {
        label: 'UserRepository',
        nodeType: 'SPRING_REPOSITORY',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/repository/UserRepository.java',
        annotations: 'JpaRepository, @Repository, findByUsername',
      },
    },
    {
      id: 'repo_order',
      type: 'custom',
      position: { x: 850, y: 200 },
      data: {
        label: 'OrderRepository',
        nodeType: 'SPRING_REPOSITORY',
        layer: 'BACKEND',
        filePath: 'src/main/java/com/codeflow/demo/repository/OrderRepository.java',
        annotations: 'JpaRepository, @Repository, findByUserId',
      },
    },
    {
      id: 'db_admin_account',
      type: 'custom',
      position: { x: 1050, y: 50 },
      data: {
        label: 'admin_accounts',
        nodeType: 'DB_TABLE',
        layer: 'DATABASE',
        filePath: 'db/schema/admin_accounts.sql',
        annotations: 'PostgreSQL Table, Primary Key: id (UUID), Indexes: idx_username',
      },
    },
    {
      id: 'db_orders_table',
      type: 'custom',
      position: { x: 1050, y: 200 },
      data: {
        label: 'orders',
        nodeType: 'DB_TABLE',
        layer: 'DATABASE',
        filePath: 'db/schema/orders.sql',
        annotations: 'PostgreSQL Table, Foreign Key: user_id -> users(id)',
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'fe_react_app', target: 'gw_security', label: '1 HTTP Request' },
    { id: 'e2', source: 'gw_security', target: 'ctrl_admin', label: '2 Dispatch' },
    { id: 'e3', source: 'ctrl_admin', target: 'svc_auth', label: '3 Invoke Service' },
    { id: 'e4', source: 'svc_auth', target: 'repo_user', label: '4 SQL Query' },
    { id: 'e5', source: 'repo_user', target: 'db_admin_account', label: '5 Persistence' },
  ],
};
