import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Layers, Sparkles, Play } from 'lucide-react';
import { Header, ThemeMode } from './components/Header';
import { IngestionModal } from './components/IngestionModal';
import { ProjectDashboard } from './components/ProjectDashboard';
import { InteractiveFlowExplorer } from './components/InteractiveFlowExplorer';
import { NodeInspectorSidebar } from './components/NodeInspectorSidebar';
import { MonacoViewerModal } from './components/MonacoViewerModal';
import { DependencyExplorerModal } from './components/DependencyExplorerModal';
import { SqlExplorerModal } from './components/SqlExplorerModal';
import { AiAssistantModal } from './components/AiAssistantModal';
import { ErDiagramModal } from './components/ErDiagramModal';
import { SecurityExplorerModal } from './components/SecurityExplorerModal';
import { FileTreeModal } from './components/FileTreeModal';
import { RuntimeTracingModal } from './components/RuntimeTracingModal';
import { Project, GraphData, NodeDetail, ProjectNode } from './types';
import { DEMO_PROJECT_DATA, DEMO_GRAPH_DATA } from './utils/demoData';

export default function App() {
  const [currentProjectId, setCurrentProjectId] = useState<string | null>(null);
  const [project, setProject] = useState<Project | null>(null);
  const [graphData, setGraphData] = useState<GraphData>({ nodes: [], edges: [] });
  const [selectedNodeId, setSelectedNodeId] = useState<string | undefined>(undefined);
  const [selectedNodeDetail, setSelectedNodeDetail] = useState<NodeDetail | null>(null);

  const [isIngestModalOpen, setIsIngestModalOpen] = useState(false);
  const [isDependencyModalOpen, setIsDependencyModalOpen] = useState(false);
  const [isSqlExplorerOpen, setIsSqlExplorerOpen] = useState(false);
  const [isAiAssistantOpen, setIsAiAssistantOpen] = useState(false);
  const [isErDiagramOpen, setIsErDiagramOpen] = useState(false);
  const [isSecurityFlowOpen, setIsSecurityFlowOpen] = useState(false);
  const [isFileTreeOpen, setIsFileTreeOpen] = useState(false);
  const [isRuntimeTracingOpen, setIsRuntimeTracingOpen] = useState(false);
  const [viewingFilePath, setViewingFilePath] = useState<string | null>(null);

  const [currentTheme, setCurrentTheme] = useState<ThemeMode>('NIGHT');

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', currentTheme);
  }, [currentTheme]);

  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<ProjectNode[]>([]);

  const handleLoadDemoProject = () => {
    setCurrentProjectId(DEMO_PROJECT_DATA.id);
    setProject(DEMO_PROJECT_DATA);
    setGraphData(DEMO_GRAPH_DATA);
    setSelectedNodeId(undefined);
    setSelectedNodeDetail(null);
  };

  useEffect(() => {
    if (!currentProjectId || !searchQuery.trim()) {
      setSearchResults([]);
      return;
    }

    const timer = setTimeout(() => {
      axios
        .get<ProjectNode[]>(`/api/v1/projects/${currentProjectId}/search?q=${searchQuery}`)
        .then((res) => setSearchResults(res.data))
        .catch(() => setSearchResults([]));
    }, 300);

    return () => clearTimeout(timer);
  }, [currentProjectId, searchQuery]);

  const handleSelectSearchResult = (nodeId: string) => {
    setSelectedNodeId(nodeId);
    setSearchQuery('');
    setSearchResults([]);
  };

  const handleExitProject = () => {
    setCurrentProjectId(null);
    setProject(null);
    setGraphData({ nodes: [], edges: [] });
    setSelectedNodeId(undefined);
    setSelectedNodeDetail(null);
  };

  useEffect(() => {
    if (!currentProjectId) return;

    if (currentProjectId === DEMO_PROJECT_DATA.id) {
      setProject(DEMO_PROJECT_DATA);
      setGraphData(DEMO_GRAPH_DATA);
      return;
    }

    axios
      .get<Project>(`/api/v1/projects/${currentProjectId}`)
      .then((res) => setProject(res.data))
      .catch((err) => console.error('Failed to fetch project:', err));

    axios
      .get<GraphData>(`/api/v1/projects/${currentProjectId}/graph`)
      .then((res) => setGraphData({ nodes: res.data?.nodes || [], edges: res.data?.edges || [] }))
      .catch((err) => console.error('Failed to fetch graph data:', err));
  }, [currentProjectId]);

  useEffect(() => {
    if (!currentProjectId || !selectedNodeId) {
      setSelectedNodeDetail(null);
      return;
    }

    axios
      .get<NodeDetail>(`/api/v1/projects/${currentProjectId}/nodes/${selectedNodeId}`)
      .then((res) => setSelectedNodeDetail(res.data))
      .catch((err) => console.error('Failed to fetch node detail:', err));
  }, [currentProjectId, selectedNodeId]);

  const handleExportMarkdown = () => {
    if (!currentProjectId || !project) return;
    const markdownContent = `# Architectural Documentation: ${project.name}
Generated by CodeFlow Studio v3.0.0

## Project Overview
- **Name**: ${project.name}
- **Status**: ${project.status}
- **Progress**: ${project.progressPercentage}%
- **Total Controllers**: ${project.controllerCount}
- **Total Services**: ${project.serviceCount}
- **Total Repositories**: ${project.repositoryCount}

## Architectural Nodes (${graphData.nodes?.length || 0})
${(graphData.nodes || []).map((n) => `- **${n.data?.label || n.id}** (${n.data?.nodeType || 'Node'}) - ${n.data?.filePath || 'Internal'}`).join('\n')}
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/\s+/g, '-')}-architecture.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-screen w-screen overflow-hidden flex flex-col bg-slate-950 text-slate-100">
      <Header
        currentProjectName={project?.name}
        currentProjectId={currentProjectId}
        onLoadDemo={handleLoadDemoProject}
        onOpenIngestModal={() => setIsIngestModalOpen(true)}
        onOpenDependencies={() => setIsDependencyModalOpen(true)}
        onOpenSqlExplorer={() => setIsSqlExplorerOpen(true)}
        onOpenAiAssistant={() => setIsAiAssistantOpen(true)}
        onOpenErDiagram={() => setIsErDiagramOpen(true)}
        onOpenSecurityFlow={() => setIsSecurityFlowOpen(true)}
        onOpenFileTree={() => setIsFileTreeOpen(true)}
        onOpenRuntimeTracing={() => setIsRuntimeTracingOpen(true)}
        onExportMarkdown={handleExportMarkdown}
        onExitProject={handleExitProject}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        searchResults={searchResults}
        onSelectSearchResult={handleSelectSearchResult}
        currentTheme={currentTheme}
        onThemeChange={setCurrentTheme}
      />

      {/* Main Content Workspace */}
      <div className="flex-1 flex overflow-hidden">
        {!currentProjectId ? (
          /* Empty State Welcome Screen */
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
            <div className="w-20 h-20 rounded-3xl bg-gradient-to-tr from-pink-600 via-purple-600 to-indigo-500 flex items-center justify-center shadow-2xl glow-indigo mb-6 animate-pulse-subtle">
              <Layers className="w-10 h-10 text-white" />
            </div>

            <h2 className="text-3xl font-extrabold text-white max-w-xl leading-tight">
              Interactive Execution Flow Explorer for Spring Boot & React
            </h2>
            <p className="text-sm text-slate-400 max-w-lg mt-3 leading-relaxed">
              Step-by-step visual execution flow tracing with interactive playback, annotation breakdowns, ERD Explorer, Security Flow, AI Assistant, and source code viewer.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row items-center space-y-3 sm:space-y-0 sm:space-x-4">
              <button
                onClick={handleLoadDemoProject}
                className="flex items-center space-x-2 px-6 py-3 rounded-xl bg-gradient-to-r from-pink-600 via-purple-600 to-indigo-600 hover:from-pink-500 hover:to-indigo-500 text-sm font-bold text-white shadow-xl shadow-pink-600/40 transition-all transform hover:scale-105"
              >
                <Play className="w-4 h-4 fill-white" />
                <span>🎮 Launch Interactive Demo Flow</span>
              </button>

              <button
                onClick={() => setIsIngestModalOpen(true)}
                className="flex items-center space-x-2 px-6 py-3 rounded-xl bg-slate-900 border border-slate-700 hover:border-indigo-500 text-sm font-bold text-slate-200 shadow-xl transition-all transform hover:scale-105"
              >
                <Sparkles className="w-4 h-4 text-indigo-400" />
                <span>Import GitHub Repo / ZIP</span>
              </button>
            </div>
          </div>
        ) : (
          /* Active Project Canvas & Inspector */
          <div className="flex-1 flex flex-col overflow-hidden">
            {project && <ProjectDashboard project={project} currentTheme={currentTheme} />}

            <div className="flex-1 flex overflow-hidden">
              <InteractiveFlowExplorer
                graphData={graphData}
                onSelectNode={(nodeId) => setSelectedNodeId(nodeId)}
                selectedNodeId={selectedNodeId}
                onViewCode={(path) => setViewingFilePath(path)}
                currentTheme={currentTheme}
              />

              {selectedNodeDetail && (
                <NodeInspectorSidebar
                  nodeDetail={selectedNodeDetail}
                  onClose={() => setSelectedNodeId(undefined)}
                  onViewCode={(path) => setViewingFilePath(path)}
                />
              )}
            </div>
          </div>
        )}
      </div>

      {/* Modals */}
      <IngestionModal
        isOpen={isIngestModalOpen}
        onClose={() => setIsIngestModalOpen(false)}
        onProjectIngested={(projectId) => {
          setCurrentProjectId(projectId);
          setSelectedNodeId(undefined);
        }}
      />

      <MonacoViewerModal
        projectId={currentProjectId!}
        filePath={viewingFilePath}
        onClose={() => setViewingFilePath(null)}
      />

      <DependencyExplorerModal
        projectId={currentProjectId}
        isOpen={isDependencyModalOpen}
        onClose={() => setIsDependencyModalOpen(false)}
      />

      <SqlExplorerModal
        projectId={currentProjectId}
        isOpen={isSqlExplorerOpen}
        onClose={() => setIsSqlExplorerOpen(false)}
      />

      <AiAssistantModal
        projectId={currentProjectId}
        isOpen={isAiAssistantOpen}
        onClose={() => setIsAiAssistantOpen(false)}
      />

      <ErDiagramModal
        projectId={currentProjectId}
        isOpen={isErDiagramOpen}
        onClose={() => setIsErDiagramOpen(false)}
      />

      <SecurityExplorerModal
        projectId={currentProjectId}
        isOpen={isSecurityFlowOpen}
        onClose={() => setIsSecurityFlowOpen(false)}
      />

      <FileTreeModal
        projectId={currentProjectId}
        isOpen={isFileTreeOpen}
        onClose={() => setIsFileTreeOpen(false)}
        onViewCode={(path) => {
          setIsFileTreeOpen(false);
          setViewingFilePath(path);
        }}
      />

      <RuntimeTracingModal
        projectId={currentProjectId}
        isOpen={isRuntimeTracingOpen}
        onClose={() => setIsRuntimeTracingOpen(false)}
        currentTheme={currentTheme}
      />
    </div>
  );
}
